#Arreglos y clases
##Matrices

una matriz es un arreglo de mxn elementos

\begin{bmatrix}
a_{11} & a_{12} & \cdots & a_{1n} \\
a_{21} & a_{22} & \cdots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \cdots & a_{mn}
\end{bmatrix}


In [1]:
A=[[1,2,3],[4,5,6],[7,8,9]]
print (A)
type (A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


list

In [2]:
B=[[21,34,40],[71,17,77],[73,81,28]]
print (A+B)

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [21, 34, 40], [71, 17, 77], [73, 81, 28]]


In [3]:
2*A

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [4]:
A[0][0]

1

##vetores y listas

In [7]:
L=A[0]
M=B[0]
L+M

[1, 2, 3, 21, 34, 40]

In [8]:
a=L[0]
b=M[0]
a+b

22

In [9]:
a==1

True

### Suma de vectores

In [10]:
len(L)==len(M)

True

In [12]:
suma=[L[0]+M[0],L[1]+M[1],L[2]+M[2]]
suma

[22, 36, 43]

In [14]:
suma=[L[i]+M[i] for i in range(3)]
suma

[22, 36, 43]

###Creacion de funciones globales
La funcion para crear funciones es `def`que se cierra con un debug (`print`o `return`)

In [15]:
def Hola():
  print ("Hola, me llamo Jon")

In [16]:
Hola()

Hola, me llamo Jon


In [19]:
def Saludar(s,n):
  print (f"Hola me llamo {s} y tengo {n} años ")

In [20]:
Saludar ("Jon", 18)

Hola me llamo Jon y tengo 18 años 


In [25]:
def par(x):
  for x in range (10):
    if x%2==0:
      print (f"{x} es par")
    else:
      print (f"{x} es impar")

In [26]:
par(6)

0 es par
1 es impar
2 es par
3 es impar
4 es par
5 es impar
6 es par
7 es impar
8 es par
9 es impar


In [27]:
def suma_vectorial (L,M):
  x=[L[i]+M[i] for i in range(3)]
  return x

In [28]:
L=[1,2,3]
M=[21,34,40]
suma_vectorial (L,M)

[22, 36, 43]

## Modulo o librerias

In [29]:
import math
from math import *

In [30]:
sqrt(68)

8.246211251235321

In [31]:
pi

3.141592653589793

#El modulo NumPy
La funcion `array`

In [32]:
import numpy as np
L_vector=np.array(L)
M_vector=np.array(M)

L_vector+M_vector

array([22, 36, 43])

In [33]:
C=[ 9,2,2,2,3,3,2,17,2]
A=[8,1,1,1,2,2,1,16,1]

C_matriz=np.array(C).reshape(3,3)
A_matriz=np.array(A).reshape(3,3)

print(C_matriz)
print(A_matriz)

[[ 9  2  2]
 [ 2  3  3]
 [ 2 17  2]]
[[ 8  1  1]
 [ 1  2  2]
 [ 1 16  1]]


In [34]:
C_matriz @ A_matriz

array([[76, 45, 15],
       [22, 56, 11],
       [35, 68, 38]])